language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJW4OZQ4RRWBJNCDA
  secret_access_key:
    secure: sAGPq7z7sMKq4k/mx7gbveQkIRM3HVMrU6iJyfBJt/0oMm9HLxZJjzeURhnNZlesQ5LsHXUzYRxRBDknyi77SU40V3/NGNhPPOWK1BGvm58LO0PpbuqEQmKOnbFPTurdU17DB8DGyQcBeMm0JeimyIuLDR0Mx7SEhw5+9PiLCQjmm8p9MN49HiNnpZ/fmB7bcWulZGTgBrE/dxfygtGTSPqItCCOj9pGO8F3lvJ/rKa1a98wGU1865ybTYUK6VciaGAzFtK6btElyZGeII/H7o23dFIdlqPDfcMOQjWVefh+lvljNFad/INnbnLdaYdjSdPQM+3h3fUgtlBk6kpbCdN0zIM2PHPMXaDmforxxSj0GZVfYqVJMjPOyh38INkmx6d3eRSh8kvwvGNP6odwyq90MG6OpRBuq8lApRMhF5U+1QFpGXJSsjPclPq0thbZxTtYFWVwfG7cmSE+IkWNLhNEKnpMS1IR3+YnexZ19o3X4tr9UuQX2xYL5JgM4p79w0sqVq2w5gxFsUa9kLJQbeTLWJAQeVDlrn+vg7kt9YHLz835v/8TSCsQbkfz61IcaKhr1Qimknfu3XHLXj/8xlxbx6BOIRGT4KVdo+EI9h0QvrRTiMc1x/kF8VvZJb78THFstc4ssOis3rPk1pUQZnv5AiWn6dght1zB4qE6v6Y=
  bucket: deploy-weeia
  upload-dir: gradzki/workerAPP
  acl: public_read
  on:
    repo: marcingradzki/ciTestGradzki2
