language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJW4OZQ4RRWBJNCDA
  secret_access_key:
    secure: DUjH9l3kL/SBCBP5O8w74L/3U0L+3aKwGcAtFZSdPUxB9I35lq5t8DJUvbogEhznigqPwQ/KaXuSVxX6Ih59608DfXx68ZBCy7MfLkEjRR7B3eKGV40WORlEycuzHLQ1uYTnAkxwaJ5yW8SAohB90wvgLiIxV6bSzN9CSKHeSkTcuehLi3R+pZF0dA5sIpidoKwTIKPIjkMpFiR8duoj01fusfHszlU6vdWoFF4qpNuG/YBiTAlL9PtyjQNX25G38OcUqGihC3Wb5/XEjZrNfMEbVEkLhQB+mLtH8t7/HR+I7j1Nr5SLe4TuzFwXTdyN/GJ2h3OOlfJgUn5+F2yFb9e+zRsohYl5JdR3RrQYb1AbBZy0S1AXzDgKTI76zWqvtxqX6NP4LRu2rpC5agej0WqeUqJNB1V0dc9sqIhrDYoRos1O9QNFHT8B4RLpz04vHK0ei5wL25836F2YKoCWkoQ4p4pmYCGEuU6c5F1x5tO014FCGjbieGnCOwu73V+mKB+ALi81sjVpvQ4Hc3+q9rmpnQDt6sKENjlodaxrt5BayziC7jLwPO57Jk2Wnlh+5G9GxpYion4qmJcXOMexjvCmeCqDlylFDuT2+IG50fCv+R3BjQF2N0Gj8YHGefdVo/AoG4FlksJiBMlcJ8OSft0eUC3OvcHlynW53VWfY/g=
  bucket: deploy-weeia
  upload-dir: marcin.gradzki/workerAPP
  acl: public_read
  on:
    repo: marcingradzki/ciTestGradzki2
