language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJW4OZQ4RRWBJNCDA
  secret_access_key:
    secure: A05UBrX4ukB9eoajfzsZY8+Rq10dLRubdRWx1GLySnX6fzpqp6hGPXopy2X7/4LI1pB8iSz0a1qCQE7vRmdNr5l+uN8bv/EWAto6c9E43CD0baRzPcnONGzNS1sMKO0231RIKNKcwg1xxdMNop1bvN7CIkbNtiGQacsXPzs0MrUergwMdeuKbRRh1FQVYf4m2Xg/I+8UHgC6sovtuKvTA8eJtdEfhNBJTbzD4G1cmHYon8LPtEpkeTQhWGpPIGyd7jDHZVjgDnUSGvxY4QLq0u1wK4lwAnQSpSp1VoxMen2KOxpoMWvHZH7nLyOk7UCZeHC8G1Nv+Ms2Rb+ondcPij7HI8Sj3tzyMknKxTSVfDMUTcXA5AidC2X6/Tw4kbaa5L5FmFFIa4y7HDs2HCbhAP9YKNmWQxFUXMjNmLacV8SR/uzlh9r8E1q6r9YC2czGv2FcXALZgFZPQ2q65EBBE9CMjSwfvIOPN9qBG83HMtnIY0SW6uW0WRCIRQ65LJAj7AsayGKxhPFwjvZkb8K+v/Ows1gxqRf9Ta1AvyUI/wBNn/uHN0NhWa+izxKRGT3wK0Hc//zjvNb9sSVz6VLvEZ747/AWvAhGamzkX+pljWRmD+Vit7JuWCf9DdG/x0RTTv/fTzM/0+j9bh2diukI5EYT2OjMSFtNByV/S/FDwLE=
  bucket: deploy-weeia
  upload-dir: marcin.gradzki/workerAPP
  acl: public_read
  on:
    repo: marcingradzki/ciTestGradzki2
