language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJW4OZQ4RRWBJNCDA
  secret_access_key:
    secure: mhP9PPh4Q2kP8Y2h6rTbVDeSKEDh0dG9YIM4xkr9VL9VA4QbyFZ7Pk6gcmRHolOOOyd9ldwgEXrKMAthGc1ZbWMfq6ABYmITzHUnDufxY7RYjMNPjhCx57bA3JvRHeYO4VN/gDBubJcnPElcNM151zU+yi2MzWZNKLpayGilqRau40m4QGA5Ex9i848+X1mW6X3EuLR0OexGoGZqvji9L2+Z+fJwFHUQ/urSOQGYrxEdcpZ9wPCbAd/yjtpvMzhYMBd4jziLy+a3nUMxudzbXPLqeQ52QMlMsXz9coKJXnFiEdFFGn1tzoQsw8H3GiDh4wqG0+JsORFCd51WoLu11PRn2LjaJ70rjyi2qEUBzN/F8dXKO8q+FL6q0L9etoowj5XpOHwwFnUiUIGur2juabhQOP3pkjLS6UwO35/xILH5VMno1VsqRRAFzKaTLUGZpNnRFTZ9fPBzYBD3650htn4wRZ1WJa05BcEFKrIjGo3eGS7u9doRwPwCOYBPETJjJ6yg5IH5hoLiKRvcp0moKB2bVh3Tmp0pweaNLMdEd8M6Pr78LVv00RRIJ3yrYxntqzbwH7PN3nM649E3z5jVUwrj6ZbyCkrTjzRGPGiGy54TCMtmk3nXnNqXKdOxQ4QXErHWa65qYXuavGKCHWaYLycJWQ4WsG3bxM5KYmF09O4=
  bucket: deploy-weeia
  upload-dir: marcin.gradzki
  acl: public_read
  on:
    repo: marcingradzki/ciTestGradzki2
