language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJW4OZQ4RRWBJNCDA
  secret_access_key:
    secure: bPC/NvY2VY+5QxWAF3qvqwQseVQLlLNe/BBVxp8uednpfGBWSB6FTlZIcD8zLtlhbgeF2rrnNIUmTFjk57r0IJZtP1OF7ogXOZMXtB2E545Wv8bFb6zm44GhMTupMfucBTcpJxtZRdjF2YeygtPWXZUxwwrjXJCe4XTTpH9GeVCVwXXHDrI4a2IKXJrBoe4YSLFKn2mM4QwAX/bgtX2LLRhJJlH0iDVP163XGi7ePPX2Lm5tdpb4lGtx1ERr1qgUSl6up2tgTkbTJBRHFmJ2LbS9MSjOs6c70U3om0mrieas5ahASABoBNlMUcB5DCEw6GQHZmLwzIJ9jm38W+F/ga3oQB+OA0oPfuBEqp7s2P6s7+FbKL7hIVXbWtxaQwf953nxldB5wD8VSZDCrHEWjABMIE38CVG1IXw+bUAk93KLrFTbt9frsv3lJ9Urn+FB0qlcoUvDaajB4L1g2Ch/PlyVYzK0+BVtOjzWJ6Q6iHrLKV4NVjOXjet5VNR+gMVOjer0zDw/4enWZYgEnAr18h86upsXONH6ULEc9ae4Zy/4PcG5EzIOr3XtjTUfJ3SQd8zUotw4VVVNb3Zm8yszyZcMFTMo/B5oH+hyUkd8G0GLZ7UwZkz2+xDzX1053/xUWqh8+FcXB5hPjJHWoI/pubwwWtpmBdAa2HREytQzQTE=
  bucket: deploy-weeia
  upload-dir: marcin.gradzki
  acl: public_read
  on:
    repo: marcingradzki/ciTestGradzki2
